[트리] 5월 23일 -ing
Altu-Bitu-2/Altu-Bitu-2_Assignment-repo pull request #14
Opened 2022-05-23 03:03 UTC by yjk395

#### 내용 & 질문
> 5639는 시간/메모리 초과, 1068이랑 15631은 틀린 상태입니다ㅠ 나머지 문제는 이후 더 풀어서 제출하겠습니다, 감사합니다.

#### <기존 제출>
> 1713, 5639, 1068, 15681

#### <추가 제출>
>

2022-05-23 06:27 UTC, bsa0322 requested changes
안녕하세요 예진님 😊 매번 열심히 해주셔서 감사합니다! 🥰 늘 느끼는 건데 코드 구현 능력이 정말 좋으신 것 같아요!! 너무 깔끔하게 짜주신 부분도 있어 감탄하며 리뷰했네요 😳

틀리신 부분에 대해서 각 문제마다 코멘트 달았습니다! 확인 후, 질문 있으시거나 수정하시면 저 다시 리뷰어로 호출 부탁드려요~! 나머지 코멘트는 가독성 정도에서의 피드백이니 참고해주시면 좋을 것 같습니다. 이번 과제도 수고하셨습니다 ❤

2022-05-23 06:27 UTC, bsa0322 commented on 05월 17일 - 트리/1068.cpp
> +map<int, vector<int>> tree; //트리
p2. map은 vector보다 메모리를 많이 차지해요! 따라서 map은 정점의 번호가 일정하지 않거나, int형이 아닌 다른 자료형일 때 등 꼭 필요한 경우에 사용하는 편이 좋아요! 해당 문제는 트리의 정점 번호가 연속이니 2차원 vector를 사용해서 트리를 구현하면 조금 더 메모리를 아낄 수 있을 것 같습니다~!

2022-05-23 06:27 UTC, bsa0322 commented on 05월 17일 - 트리/1068.cpp
> +    }
해당 문제의 틀린 부분에 대해 코멘트 남깁니다! 문제에서 루트 정점이 항상 0번이라는 언급이 있었을까요? 이 부분만 확인하시면 바로 해결하실 수 있을 것 같네요~!

2022-05-23 06:27 UTC, bsa0322 commented on 05월 17일 - 트리/1068.cpp
> +    return cnt;
로직 완벽해요!! 🥰 리프 노드가 생기는 경우까지 너무 잘 처리해주셨습니다!! 👍👍

2022-05-23 06:27 UTC, bsa0322 commented on 05월 17일 - 트리/15681.cpp
> +    }
p1. 컨테이너에 대한 탐색을 진행하는 반복문 안에서 원소를 삭제하면 오류가 날 가능성이 매우 높아요! 생각지도 못한 인덱스 에러나 내가 원하는 대로 탐색이 잘 안될 수도 있구요. 해당 방식 대신 새로운 트리를 구성하는 방식으로 하는 건 어떨까요?

2022-05-23 06:27 UTC, bsa0322 commented on 05월 17일 - 트리/15681.cpp
> +}
p1. 해당 문제는 입력 범위가 크기 때문에 서브트리에 속한 정점의 수를 매번 새로 구하는 현재 방식으로는 시간초과가 날 거예요! 메모리제이션을 활용해 볼까요? 각 정점의 서브트리 수를 매번 저장한 다음에, 이미 값이 존재한다면 값을 리턴해주면 되겠어요! 이런 형식은 재귀를 활용한 dp에서도 많이 봤었죠 😉

2022-05-23 06:27 UTC, bsa0322 commented on 05월 17일 - 트리/1713.cpp
> +        rcm_order++;
p2. rcm_order는 반복마다 매번 증가하고 있네요~! 반복문의 인자로 활용해도 좋을 것 같아요 😊 그럼 while반복문이 아니라 다른 게 필요하겠네요!

2022-05-23 06:27 UTC, bsa0322 commented on 05월 17일 - 트리/1713.cpp
> +        }
함수를 아주 잘 활용해주셨네요!!! 덕분에 좋은 함수 알아가네요~!!! 저희가 준비한 샘플코드보다 훨씬 코드가 깔끔해요! 최고입니다 🥰🤩

2022-05-23 06:27 UTC, bsa0322 commented on 05월 17일 - 트리/5639.cpp
> +    node->left = node->right = NULL;
p1. 현재 매번 새로운 node를 만들어줘서 메모리 초과가 나고 있어요! 검사를 할 때 매번 node를 삽입해주지 않는데, 만들어놓으면 사용하지 않은 node가 메모리에 많이 쌓일 거예요.
어느 곳에서 node를 생성하고 사용해야 적절할까요?

2022-05-24 09:01 UTC, yjk395 commented
수정하였습니다! 15681번은 입출력 속도 향상 코드도 추가해야 했었네요😱 남아있던 필수과제 하나도 어제 제출했습니다! 항상 감사합니다😊😊

2022-05-25 07:45 UTC, bsa0322 approved these changes
확인이 늦었네요 죄송합니다ㅜㅜ 
수정해주신 부분 모두 확인했습니다! 제가 말씀드린 부분을 아주 잘 캐치해주셨어요. 🥰
조금 더 리팩토링할 수 있는 부분은 간단한 코멘트 남겼습니다! 
자유롭게 수정하신 후 머지해주세요! 수고하셨습니다~! 😍

2022-05-25 07:45 UTC, bsa0322 commented on 05월 17일 - 트리/15681.cpp
> +    if (node_size[cur] != -1) return node_size[cur]; //이미 탐색(=부모)
이미 탐색한 것은 부모 정점을 거르기 위함도 있지만, 해당 정점을 루트로 했을 때의 서브 트리 정점이 이미 계산된 경우를 말합니다~!

2022-05-25 07:45 UTC, bsa0322 commented on 05월 17일 - 트리/15681.cpp
> +}
원래 작성해 주신 코드에서도 충분히 리팩토링 할 수 있어요!! 지금은 매번 재귀호출을 하고 저장한 node_size값을 사용하지 않고 있어요. 따라서 매번 node_size[]값을 계산하게 되겠죠! 이미 node_size인덱스에 값이 존재한다면 리턴해주는 부분이 필요합니다! 해당 부분만 다르고 이외의 로직은 비슷하다고 볼 수 있어요 😊

2022-05-25 07:45 UTC, bsa0322 commented on 05월 17일 - 트리/5639.cpp
> +        }
좋아요~~! 삽입하는 곳에서 node를 생성해야 메모리 초과를 방지할 수 있었죠! 😊 
해당 부분이 중복되니, 우선 재귀 호출을 하고 현재 node값이 NULL이면 데이터를 삽입하는 형식으로 코드를 짜볼 수 있을 것 같아요~!!! 샘플코드 참고해주셔도 좋을 것 같습니다 🥰

2022-05-26 07:43 UTC, merged